### ISSUE TITLE
Action system redesign

### ISSUE THREAD

**Issue by kidk** [kidk/felt#30]
The action system needs a bit of a rework. I want to make it more flexible and have it fit the browser system a bit more. Converting the system to yaml will also allow a user to leave comments in the file without the need for the `commentjson` module.

Couple of examples:
```
# Old method
  - action: set_value
    selector: input[name=password]
    value: isAWESOME

# New method
  - action: set
    select: "input[name=password]"
    attribute: value
    value: isAWESOME
```

```
# Old method
  - action: sleep
    value:
      min: 1000
      max: 5000

# New method
  - action: wait
    time: 
      min: 1000
      max: 5000

# This replaces wait_for_element
  - action: wait
    select: "#element" 
    time:
      min: 1000
      max: 5000  
```

```
# Old method
  - action: submit
    selector: "#loginForm"

# New method
  - action: event
    type: submit
    select: "#loginForm"
```
